In [1]:
import torch

x = torch.empty(2, 3)
print("empty:", x)

x = torch.rand(2, 3)
print("rand:", x)

x = torch.zeros(2, 3)
print("zeros:", x)

# dtype: int, double, float16
x = torch.ones(2, 3, dtype=torch.double)
print("ones(.., dtype=float16):", x)

x = torch.tensor([2.5, .1])
print(x)

empty: tensor([[0., 0., 0.],
        [0., 0., 0.]])
rand: tensor([[0.6189, 0.7319, 0.9119],
        [0.2403, 0.3462, 0.0097]])
zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones(.., dtype=float16): tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([2.5000, 0.1000])


In [2]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)
z = x+y
print(z)
z = torch.add(x,y)
print(z)


# trailing underscore: in place operation (modity variable)
y.add_(x) # y = x + y
print(y)

z = x-y
z = torch.sub(x,y)
x.sub_(y) # x = x - y

z = x*y
z = torch.mul(x,y)
x.mul_(y) # x = x * y

z = x/y
z = torch.div(x,y)
x.div_(y) # x = x / y


tensor([[0.8380, 1.1233],
        [1.1290, 1.1018]])
tensor([[0.8380, 1.1233],
        [1.1290, 1.1018]])
tensor([[0.8380, 1.1233],
        [1.1290, 1.1018]])


tensor([[-0.3799, -0.6608],
        [-0.6776, -0.9190]])

In [ ]:
import torch

# slicing
x = torch.rand(5, 3)
# first column
print(x[:, 0])

# first row
print(x[0, :])

# second row
print(x[1, :])

# element(1,1) as a tensor
print(x[1,1])
# element(1,1) as an actual value
print(x[1,1].item())


In [ ]:
import torch

# reshape
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

# don't specify in first dimension, then pytorch determines for you
# torch.Size([2, 8])
y = x.view(-1, 8)
print(y.size())



In [1]:
# Convert between numpy <-> torch.tensor
import torch
import numpy as np

# 1. torch -> numpy
a = torch.ones(5)
print(a)
print(type(a))

b = a.numpy()
print(b)
print(type(b))

# if tensor is on CPU and not on GPU,
# object will be on the same location
# CHANGING `b` will also change `a` and vice versa!
a.add_(1)
print(a)
print(b)

# 2. numpy -> torch
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
a += 1
print(a)
print(b)

if torch.cuda.is_available():
    print(torch.cuda.is_available())
    # specify cuda device
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    # performed on GPU which is much faster
    z = x+y
    # ERORR: NUMPY CAN only handle CPU tensor
    # z.numpy()
    z = z.to("cpu")


tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [2]:
import torch
import numpy as np

x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
